inherit_from: ./.rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/**

Style/Documentation:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 13
